# Generated by Django 5.2.17 on 2026-09-16 08:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=16, unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Bachelor", "Bachelor"),
                            ("Master", "Master"),
                            ("Diploma", "Diploma"),
                            ("Certificate", "Certificate"),
                        ],
                        max_length=16,
                    ),
                ),
                ("department", models.CharField(max_length=120)),
                ("affiliation", models.CharField(max_length=120)),
                ("duration_years", models.PositiveSmallIntegerField()),
                ("semesters", models.PositiveSmallIntegerField()),
                ("seats", models.PositiveSmallIntegerField()),
                ("fee_per_year", models.PositiveIntegerField()),
                ("coordinator", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("Active", "Active"), ("Inactive", "Inactive")],
                        default="Active",
                        max_length=16,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=240),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
