# Generated by Django 5.2.17 on 2026-09-16 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollegeInfo",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "college_name",
                    models.CharField(
                        default="WhiteHouse College of Business & Technology",
                        max_length=255,
                    ),
                ),
                ("college_code", models.CharField(default="WCBT", max_length=32)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("website", models.URLField(blank=True, default="")),
                ("logo_url", models.URLField(blank=True, default="")),
                ("established_date", models.DateField(blank=True, null=True)),
                ("motto", models.CharField(blank=True, default="", max_length=255)),
                ("academic_year_start", models.PositiveSmallIntegerField(default=1)),
                ("max_students_per_program", models.PositiveIntegerField(default=500)),
                ("enable_email_notifications", models.BooleanField(default=True)),
                ("enable_sms_notifications", models.BooleanField(default=False)),
                (
                    "default_password",
                    models.CharField(default="ChangeMe@123", max_length=128),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "College Info",
                "verbose_name_plural": "College Info",
            },
        ),
    ]
