# Generated by Django 5.2.17 on 2026-09-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collegesettings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collegeinfo",
            name="catalog",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="collegeinfo",
            name="permissions",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
